apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-loadbalancer-config
data:
  nginx.conf: |
    events {}
    http {
        upstream myapps {
            server terraform-service.default.svc.cluster.local:80 weight=90;
            server webapp-service.default.svc.cluster.local:80  weight=30;
        }
        server {
            listen 80;
            location / {
                proxy_pass http://myapps;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-lb
  template:
    metadata:
      labels:
        app: nginx-lb
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-loadbalancer-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
spec:
  type: NodePort
  selector:
    app: nginx-lb
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
