apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps-ingress
spec:
  rules:
  - host: myapps.local
    http:
      paths:
      - path: /terraform
        pathType: Prefix
        backend:
          service:
            name: terraform-service
            port:
              number: 80
      - path: /webapp
        pathType: Prefix
        backend:
          service:
            name: webapp-service
            port:
              number: 80
